# Generated by Django 3.2.3 on 2023-07-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(verbose_name='Текст поста'),
        ),
    ]
