# Generated by Django 3.2.3 on 2023-07-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20230715_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='task',
            name='pub_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
