# Generated by Django 3.2.3 on 2023-07-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20230717_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='update_date',
            field=models.DateTimeField(default=models.DateTimeField(auto_now_add=True)),
        ),
    ]
