# Generated by Django 3.2.3 on 2023-07-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_task_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
