# Generated by Django 3.2.3 on 2023-07-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_task_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('New', 'Создана'), ('In_Progress', 'В работе'), ('Completed', 'Ответ')], default='New', max_length=12),
        ),
    ]
