# Generated by Django 3.2.3 on 2023-07-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_task_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='update_date',
        ),
    ]
